[workspace]
resolver = "2"
members = ["src-tauri", "crates/protocol", "crates/hook-cli"]

[workspace.package]
version = "0.1.0"
edition = "2021"

# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
